# Generated by Django 5.0.2 on 2024-02-21 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adddata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='to100',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='PopularBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adddata.brand')),
            ],
        ),
        migrations.CreateModel(
            name='PopularCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adddata.car')),
            ],
        ),
    ]
